version: '3.8'

services:
  stock-analyzer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    restart: unless-stopped 